// Code generated by enumgen. DO NOT EDIT.

package fruits

type (
	FruitsVisitor interface {
		VisitApple(e Apple)
		VisitOrange(e Orange)
		VisitGrape(e Grape)
	}
	FruitsEnum interface {
		Accept(v FruitsVisitor)
	}
)

func (e Apple) Accept(v FruitsVisitor) {
	v.VisitApple(e)
}
func (e Orange) Accept(v FruitsVisitor) {
	v.VisitOrange(e)
}
func (e Grape) Accept(v FruitsVisitor) {
	v.VisitGrape(e)
}

var _ = []FruitsEnum{Apple{}, Orange{}, Grape{}}
