// Code generated by enumgen. DO NOT EDIT.

package event

type (
	EventHandler interface {
		OnOrderPlaced(e OrderPlaced)
		OnPaymentReceived(e PaymentReceived)
		OnItemShipped(e ItemShipped)
	}
	EventEnum interface {
		Emit(v EventHandler)
	}
)

func (e OrderPlaced) Emit(v EventHandler) {
	v.OnOrderPlaced(e)
}
func (e PaymentReceived) Emit(v EventHandler) {
	v.OnPaymentReceived(e)
}
func (e ItemShipped) Emit(v EventHandler) {
	v.OnItemShipped(e)
}

var _ = []EventEnum{OrderPlaced{}, PaymentReceived{}, ItemShipped{}}
