// Code generated by enumgen. DO NOT EDIT.

package event

type (
	EventHandler interface {
		OnOrderPlaced(e OrderPlaced) error
		OnPaymentReceived(e PaymentReceived) error
		OnItemShipped(e ItemShipped) error
	}
	EventEnum interface {
		Emit(v EventHandler) error
	}
)

func (e OrderPlaced) Emit(v EventHandler) error {
	return v.OnOrderPlaced(e)
}
func (e PaymentReceived) Emit(v EventHandler) error {
	return v.OnPaymentReceived(e)
}
func (e ItemShipped) Emit(v EventHandler) error {
	return v.OnItemShipped(e)
}

var _ = []EventEnum{OrderPlaced{}, PaymentReceived{}, ItemShipped{}}
